### ISSUE TITLE
Creating a content with menu

### ISSUE THREAD

**Issue by cloud-rocket** [MarcSkovMadsen/awesome-analytics-apps-template#3]
HI @MarcSkovMadsen ,

It's not entirely clear how to create a simple `ipywidget` or `panel` based application (a page) which will open with the side menu and title. I don't really care if clicking on the menu will just load the content or reload the whole page, but the existing examples (i.e. `hello_ipywidgets_world`) are loading on their own without title and menu.

Thanks

**Comment by cloud-rocket** [comment]
Sorry, missed this example - https://github.com/MarcSkovMadsen/awesome-analytics-apps-template/tree/main/src/apps/ipyvolume_simple

**Comment by MarcSkovMadsen** [comment]
Hi @cloud-rocket 

Thanks for input. Is there something I could document better or otherwise do to make it clearer? Or would you like the hello world examples to do a little bit more than they do now?

**Comment by cloud-rocket** [comment]
Thanks @MarcSkovMadsen ,

I'd say adding a small chapter in the readme on how to add pages to the app - https://github.com/MarcSkovMadsen/awesome-analytics-apps-template

In general I think it makes sense to create an overall intro to your effort:
* With a high level vision which you have here - https://github.com/MarcSkovMadsen/awesome-panel/issues/20
* A description and goal of each one of the projects (`awesome-panel`, `awesome-panel-extensions`, `awesome-analytics-apps-template`) 
And how they play together.
I think the obvious place is in the awesome-panel.org
